config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  namespace :admin do
    resources :employees
    resources :movies do
      resources :issues
    end
  end

  resources :transactions do
    resources :customers, only: [:index]
  end

  resources :customers do
    resources :transactions, only: [:index]
    resources :return_movies, only: [:index]
  end

  resources :rented_movies do
    resources :transactions, only: [:index]
    resources :return_movies, only: [:index]
  end

  resources :return_movies do
    resources :customers, only: [:index]
    resources :transactions, only: [:index]

  end


end

app/models/Employee.rb
class Employee < ActiveRecord::Base

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :middle_name, presence: true
  validates :status, presence: true
  validates :position, presence: true
  validates :contact_number, presence: true
  validates :address, presence:true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  validates :name,    presence: true, uniqueness: { case_sensitive: false }
  validates :gender,  presence: true
  validates :status,  presence: true
  validates :age,     presence: true
  validates :email,   presence: true
  validates :address, presence: true

  belongs_to :user
  has_many :transactions, dependent: :destroy

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  validates :movie_id, presence: true
  validates :description, presence:true

  belongs_to :movie
end

app/models/movie.rb
class Movie < ActiveRecord::Base

  validates :title,       presence: true, uniqueness: true, on: [:create,:update]
  validates :description, presence: true
  validates :total_copy,  presence: true
  validates :price,       presence: true

  has_many :transactions
  has_many :issues

end

app/models/return_movie.rb
class ReturnMovie < ActiveRecord::Base
  validates :user_id, presence: true
  validates :trasaction_id, presence: true
  validates :quantity, presence: true

  belongs_to :trasaction
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

  validates :user_id     ,presence: true
  validates :customer_id ,presence: true
  validates :movie_id    ,presence: true
  validates :quantity    ,presence: true

  validate :is_available

  belongs_to :customer
  belongs_to :user
  belongs_to :movie
  has_many :return_movies

  private
  def is_available
    movie = Movie.find(self.movie_id)
    total_rented = Transaction.where(movie_id: self.movie_id).sum(:quantity)
    available_copy = movie.total_copy - total_rented
    errors.add(:quantity,"Cannot be provided!") if !self.quantity.nil? && available_copy < self.quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customers
  has_many :transactions
  has_many :return_movies
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit,:update,:destroy,:show]

  def index
    @employees = Employee.page(params[:page]).per(10)
  end

  def show
    #set employee
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.create(employee_params)
    if @employee.save
      @account = Account.create(email: @employee.email,password: "qwer4321")
      @account.employee_id = @employee.id
      @account.save
      flash['success'] = "Employee successfuly added!"
      redirect_to admin_employees_path
    else
      render :new
    end
  end

  def edit
    #set employee
  end

  def update
    if @employee.update(employee_params)
      flash['success'] = "Employee successfuly update!"
      redirect_to admin_employees_path(page: params[:page])
    else
      render :edit
    end
  end

  def destroy
    if @employee.destroy
      flash['success'] = "Employee successfuly deleted!"
      redirect_to admin_employees_path
    end
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:first_name,:last_name,:middle_name,:status,:position,:contact_number,:address,:email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  helper_method :admin?, :staff?


  def admin?
    current_user.position == "admin"
  end

  def staff?
    current_user.position == "staff"
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:edit,:update,:destroy,:show]

  def index
    @customer = Customer.includes(:transactions).page(params[:page]).per(10)
    @customer = @customer.find(params[:transaction_id]) if params[:transaction_id]
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)
    @customer.user_id = current_user.id
    if @customer.save
      flash[:success] = "Customer successfully added!"
      redirect_to customers_path
    else
      render :new
    end
  end

  def update
    if @customer.update(customer_params)
      flash[:success] = "Customer successfully updated!"
      redirect_to customers_path(page: params[:page])
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:name,:gender,:status,:age,:email,:address)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/rented_movies_controller.rb
class RentedMoviesController < ApplicationController
  def index
    @rented_movies = Movie.includes(:transactions).page(params[:page]).per(10)
  end
end

app/controllers/return_movies_controller.rb
class ReturnMoviesController < ApplicationController
  def index
    @return_movies = ReturnMovie.includes(:transaction,:movie).page(params[:page]).per(10)
  end

  def new
    @return_movie = ReturnMovie.new
  end

  def create

  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:edit,:update]
  include RentedMoviesHelper
  def index
    @transaction = Transaction.includes(:customer,:movie).page(params[:page]).per(10)
    @transaction = @transaction.find(params[:customer_id]).page(params[:id]).per(10) if params[:customer_id]
    @transaction = @transaction.find(params[:rented_movie_id]).page(params[:id]).per(10) if params[:rented_movie_id]
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.create(transaction_params)
    @transaction.user_id = current_user.id
    if @transaction.save
      flash[:success] = "Trasanction done"
      redirect_to transactions_path(page: params[:page])
    else
      render :new
    end
  end

  private
  def transaction_params
    params.require(:transaction).permit(:customer_id,:movie_id,:quantity)
  end

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/rented_movies_helper.rb
module RentedMoviesHelper
  def available_movies(total_copy, rented_movies)
    available_copy = total_copy - rented_movies
  end
end

app/helpers/return_movies_helper.rb
module ReturnMoviesHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/employees/_form.html.erb
<%= form_for employee, url: url, method: methods do |f| %>
  <fieldset>
    <legend>Employee Information</legend>
    <div class="row">
      <div class="col-sm-4">
        <div class="form-group">
          <%= f.label :First_Name %>
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <%= f.label :LastName %>
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <%= f.label :Middle_Name %>
          <%= f.text_field :middle_name, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <div class="form-group">
          <%= f.label :status %>
          <%= f.select :status, options_for_select(["Single","Married","Complicated"]),{include_black: true},{class: "form-control"} %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <%= f.label :position %>
          <%= f.select :position, options_for_select(["Staff","Manager","Cashier"]),{include_black: true},{include_black: true, class: "form-control"} %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <%= f.label :Contact_Number %>
          <%= f.text_field :contact_number, class: "form-control" %>
        </div>
      </div>

    </div>
    <div class="form-group">
      <%= f.label :Address %>
      <%= f.text_area :address, class: "form-control", rows: "5" %>
    </div>
    <div class="form-group">
      <%= f.label :Email %>
      <%= f.text_field :email, type: "email", class: "form-control" %>
    </div>
    <div class="pull-right">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to "Back", admin_employees_path, class: "btn btn-default" %>
    </div>
  </fieldset>
<% end %>

app/views/admin/employees/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1 class="panel-title">Edit Employee</h1>
  </div>
  <div class="panel-body">
    <%= render partial: "shared/messages", locals:{obj: @employee} %>
    <%= render partial: "form", locals:{employee: @employee, url: admin_employee_path(page: params[:page]), methods: :put} %>
  </div>
</div>

app/views/admin/employees/index.html.erb
<h1>Employees</h1>
<%= link_to "Add new", new_admin_employee_path, class: "btn btn-success" %>
<br>
<br>
<table class="table table-bordered">
  <thead>
  <th width="5%">Id</th>
  <th width="60%">Name</th>
  <th width="15%">Position</th>
  <th width="20%">Action</th>
  </thead>
  <tbody>
  <% @employees.each do |employee| %>
    <tr>
      <td><%= employee.id %></td>
      <td><%= employee.last_name + "," + employee.first_name + "," + employee.middle_name %></td>
      <td><%= employee.position %></td>
      <td>
        <%= link_to "View", admin_employee_path(employee), class: "btn btn-primary" %>
        <%= link_to "Edit", edit_admin_employee_path(employee,page: params[:page]), class: "btn btn-warning" %>
        <%= link_to "Delete", admin_employee_path(employee), data: {confirm: "Are you sure to delete?"}, method: :delete, class: "btn btn-danger" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<div class="pull-right">
  <%= paginate @employees %>
</div>

app/views/admin/employees/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1 class="panel-title">Add New Employee</h1>
  </div>
  <div class="panel-body">
    <%= render partial: "shared/messages", locals:{obj: @employee} %>
    <%= render partial: "form", locals:{employee: @employee, url: admin_employees_path, methods: :post} %>
  </div>
</div>

app/views/admin/employees/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1 class="panel-title">Employee Information</h1>
  </div>
  <div class="panel-body">
    <div class="form-horizontal">
      <div class="form-group">
        <label class="col-sm-2 text-right">First Name:</label>
        <div class="col-sm-10">
          <p><%= @employee.first_name %></p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 text-right">Last Name:</label>
        <div class="col-sm-10">
          <p><%= @employee.last_name %></p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 text-right">Middle Name:</label>
        <div class="col-sm-10">
          <p><%= @employee.middle_name %></p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 text-right">Status:</label>
        <div class="col-sm-10">
          <p><%= @employee.status %></p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 text-right">Position:</label>
        <div class="col-sm-10">
          <p><%= @employee.position %></p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 text-right">Contact Number:</label>
        <div class="col-sm-10">
          <p><%= @employee.contact_number %></p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 text-right">Address:</label>
        <div class="col-sm-10">
          <p><%= @employee.address %></p>
        </div>
      </div>
    </div>
    <div class="pull-right">
      <%= link_to "Edit Employee", edit_admin_employee_path(@employee), class: "btn btn-primary" %>
      <%= link_to "Back", admin_employees_path, class: "btn btn-default" %>
    </div>
  </div>
</div>