config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  namespace :admin do
    resources :employees
    resources :movies do
      resources :issues
    end
  end

  resources :transactions do
    resources :customers, only: [:index]
  end

  resources :customers do
    resources :transactions, only: [:index]
    resources :return_movies, only: [:index]
  end

  resources :rented_movies do
    resources :transactions, only: [:index]
    resources :return_movies, only: [:index]
  end

  resources :return_movies do
    resources :customers, only: [:index]
    resources :transactions, only: [:index]

  end


end

app/models/Employee.rb
class Employee < ActiveRecord::Base

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :middle_name, presence: true
  validates :status, presence: true
  validates :position, presence: true
  validates :contact_number, presence: true
  validates :address, presence:true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  validates :name,    presence: true, uniqueness: { case_sensitive: false }
  validates :gender,  presence: true
  validates :status,  presence: true
  validates :age,     presence: true
  validates :email,   presence: true
  validates :address, presence: true

  belongs_to :user
  has_many :transactions, dependent: :destroy

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  validates :movie_id, presence: true
  validates :description, presence:true

  belongs_to :movie
end

app/models/movie.rb
class Movie < ActiveRecord::Base

  validates :title,       presence: true, uniqueness: true, on: [:create,:update]
  validates :description, presence: true
  validates :total_copy,  presence: true
  validates :price,       presence: true

  has_many :transactions
  has_many :issues

end

app/models/return_movie.rb
class ReturnMovie < ActiveRecord::Base
  validates :user_id, presence: true
  validates :trasaction_id, presence: true
  validates :quantity, presence: true

  belongs_to :trasaction
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

  validates :user_id     ,presence: true
  validates :customer_id ,presence: true
  validates :movie_id    ,presence: true
  validates :quantity    ,presence: true

  validate :is_available

  belongs_to :customer
  belongs_to :user
  belongs_to :movie
  has_many :return_movies

  private
  def is_available
    movie = Movie.find(self.movie_id)
    total_rented = Transaction.where(movie_id: self.movie_id).sum(:quantity)
    available_copy = movie.total_copy - total_rented
    errors.add(:quantity,"Cannot be provided!") if !self.quantity.nil? && available_copy < self.quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customers
  has_many :transactions
  has_many :return_movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  helper_method :admin?, :staff?


  def admin?
    current_user.position == "admin"
  end

  def staff?
    current_user.position == "staff"
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:edit,:update,:destroy,:show]

  def index
    @customer = Customer.includes(:transactions).page(params[:page]).per(10)
    @customer = @customer.find(params[:transaction_id]) if params[:transaction_id]
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)
    @customer.user_id = current_user.id
    if @customer.save
      flash[:success] = "Customer successfully added!"
      redirect_to customers_path
    else
      render :new
    end
  end

  def update
    if @customer.update(customer_params)
      flash[:success] = "Customer successfully updated!"
      redirect_to customers_path(page: params[:page])
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:name,:gender,:status,:age,:email,:address)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/rented_movies_controller.rb
class RentedMoviesController < ApplicationController
  def index
    @rented_movies = Movie.includes(:transactions).page(params[:page]).per(10)
  end
end

app/controllers/return_movies_controller.rb
class ReturnMoviesController < ApplicationController
  def index
    @return_movies = ReturnMovie.includes(:transaction,:movie).page(params[:page]).per(10)
  end

  def new
    @return_movie = ReturnMovie.new
  end

  def create

  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:edit,:update]
  include RentedMoviesHelper
  def index
    @transaction = Transaction.includes(:customer,:movie).page(params[:page]).per(10)
    @transaction = @transaction.find(params[:customer_id]).page(params[:id]).per(10) if params[:customer_id]
    @transaction = @transaction.find(params[:rented_movie_id]).page(params[:id]).per(10) if params[:rented_movie_id]
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.create(transaction_params)
    @transaction.user_id = current_user.id
    if @transaction.save
      flash[:success] = "Trasanction done"
      redirect_to transactions_path(page: params[:page])
    else
      render :new
    end
  end

  private
  def transaction_params
    params.require(:transaction).permit(:customer_id,:movie_id,:quantity)
  end

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/admin/issues_helper.rb
module Admin::IssuesHelper
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/rented_movies_helper.rb
module RentedMoviesHelper
  def available_movies(total_copy, rented_movies)
    available_copy = total_copy - rented_movies
  end
end

app/helpers/return_movies_helper.rb
module ReturnMoviesHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_form.html.erb
<%= form_for(customer, url: url, method: methods) do |f| %>
  <div class="form-group">
    <%= f.label_tag :Customer_Name %>
    <%= f.text_field :name, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label_tag :Status %>
    <%= f.select :status, options_for_select(["Single","Married","Iniwan"]),{},{class: "form-control"}%>
  </div>
  <div class="form-group">
    <%= f.label_tag :Gender %>
    <%= f.select :gender, options_for_select(["Male","Female","Di pa sure"]),{},{class: "form-control"}%>
  </div>
  <div class="form-group">
    <%= f.label_tag :Age %>
    <%= f.text_field :age,type: "number", class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label_tag :Email %>
    <%= f.text_field :email,type: "email", class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label_tag :Address %>
    <%= f.text_area :address,rows: 5, class: "form-control"%>
  </div>
  <div class="pull-right">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Back", customers_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h1 class="panel-title">Edit Customer Information</h1>
      </div>
      <div class="panel-body">
        <%= render partial: "shared/messages", locals:{obj: @customer} %>
        <%= render partial: "form", locals: {customer: @customer, url: customer_path(page: params[:page]), methods: :put} %>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<h1>Customer</h1>
<%= link_to "Add New", new_customer_path, class: "btn btn-success" %>
<br>
<br>
<table class="table table-bordered">
  <thead>
  <th width="5%">Id</th>
  <th width="55%">Customer Name</th>
  <th width="20%">Rented Movie</th>
  <th width="20">Action</th>
  </thead>
  <tbody>
  <% @customer.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= customer.name %></td>
      <td><%= link_to "#{customer.transactions.sum(:quantity)}", customer_transactions_path(customer) %></td>
      <td>
        <%= link_to "View", customer_path(customer), class: "btn btn-primary" %>
        <%= link_to "Update", edit_customer_path(customer, page: params[:page]), class: "btn btn-warning" %>
        <%= link_to "Delete", customer_path(customer), class: "btn btn-danger" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<div class="pull-right">
  <%= paginate @customer %>
</div>

app/views/customers/new.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h1 class="panel-title">Add new Customer</h1>
      </div>
      <div class="panel-body">
        <%= render partial: "shared/messages", locals:{obj: @customer} %>
        <%= render partial: "form", locals:{customer: @customer, url: customers_path, methods: :post} %>
      </div>
    </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h1 class="panel-title">Customer Information</h1>
    </div>
    <div class="panel-body">
      <div class="form-horizontal">
        <div class="form-group">
          <label class="col-sm-2 text-right">Customer Name:</label>
          <div class="col-sm-10">
            <p><%= @customer.name %></p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 text-right">Status:</label>
          <div class="col-sm-10">
            <p><%= @customer.status %></p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 text-right">Gender:</label>
          <div class="col-sm-10">
            <p><%= @customer.gender %></p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 text-right">Age:</label>
          <div class="col-sm-10">
            <p><%= @customer.age %></p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 text-right">Email:</label>
          <div class="col-sm-10">
            <p><%= @customer.email %></p>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 text-right">Address:</label>
          <div class="col-sm-10">
            <p><%= @customer.address %></p>
          </div>
        </div>
      </div>
      <div class="pull-right">
        <%= link_to "Edit Customer", edit_customer_path(@customer), class: "btn btn-primary" %>
        <%= link_to "Back", customers_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/transactions/_form.html.erb
<%= form_for transaction, url: url, method: methods do |f| %>
  <div class="form-group">
    <%= f.label :Customer_Name %>
    <%= f.select :customer_id, options_from_collection_for_select(Customer.all, :id, :name),{prompt: "Select Customer"},{class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :Movie %>
    <%= f.select :movie_id, options_from_collection_for_select(Movie.all, :id, :title),{prompt: "Select Movie"},{class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :Quantity %>
    <%= f.text_field :quantity, type: "number", class: "form-control" %>
  </div>
  <div class="pull-right">
    <%= f.submit "Rent Movie", class: "btn btn-primary" %>
    <%= link_to "Back", transactions_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h1 class="panel-title">Edit Transaction</h1>
      </div>
      <div class="panel-body">
        <%= render partial: "shared/messages", locals:{obj: @transaction} %>
        <%= render partial: "form", locals: {transaction: @transaction, url: transaction_path(page: params[:page]), methods: :put} %>
      </div>
    </div>
  </div>
</div>

app/views/transactions/index.html.erb
<h1>Transactions</h1>
<%= link_to "New Transaction", new_transaction_path, class: "btn btn-primary" %>
<br>
<br>
<table class="table table-bordered">
  <thead>
  <th width="5%">Id</th>
  <th width="45">Customer Name</th>
  <th width="20%">Movie</th>
  <th width="10%">Quantity</th>
  <th width="20%">Action</th>
  </thead>
  <% @transaction.each do |transaction| %>
    <tr>
      <td><%= transaction.id %></td>
      <td><%= transaction.customer.name %></td>
      <td><%= transaction.movie.title %></td>
      <td><%= transaction.quantity %></td>
      <td>
        <%= link_to "Update", edit_transaction_path(transaction, page: params[:page]), class: "btn btn-warning" %>
        <%= link_to "View Customer",customer_path(transaction),class: "btn btn-primary" %>
      </td>
    </tr>
  <% end %>
</table>
<div class="pull-right">
  <%= paginate @transaction %>
</div>

app/views/transactions/new.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h1 class="panel-title">New Transaction</h1>
      </div>
      <div class="panel-body">
        <%= render partial: "shared/messages", locals:{obj: @transaction} %>
        <%= render partial: "form", locals:{transaction: @transaction, url: transactions_path, methods: :post} %>
      </div>
    </div>
  </div>
</div>