config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  namespace :admin do
    resources :employees
    resources :movies do
      resources :issues
    end
  end

  resources :transactions do
    resources :customers, only: [:index]
  end

  resources :customers do
    resources :transactions, only: [:index]
    resources :return_movies, only: [:index]
  end

  resources :rented_movies do
    resources :transactions, only: [:index]
    resources :return_movies, only: [:index]
  end

  resources :return_movies do
    resources :customers, only: [:index]
    resources :transactions, only: [:index]

  end


end

app/models/Employee.rb
class Employee < ActiveRecord::Base

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :middle_name, presence: true
  validates :status, presence: true
  validates :position, presence: true
  validates :contact_number, presence: true
  validates :address, presence:true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  validates :name,    presence: true, uniqueness: { case_sensitive: false }
  validates :gender,  presence: true
  validates :status,  presence: true
  validates :age,     presence: true
  validates :email,   presence: true
  validates :address, presence: true

  belongs_to :user
  has_many :transactions, dependent: :destroy

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  validates :movie_id, presence: true
  validates :description, presence:true

  belongs_to :movie
end

app/models/movie.rb
class Movie < ActiveRecord::Base

  validates :title,       presence: true, uniqueness: true, on: [:create,:update]
  validates :description, presence: true
  validates :total_copy,  presence: true
  validates :price,       presence: true

  has_many :transactions
  has_many :issues

end

app/models/return_movie.rb
class ReturnMovie < ActiveRecord::Base
  validates :user_id, presence: true
  validates :trasaction_id, presence: true
  validates :quantity, presence: true

  belongs_to :trasaction
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

  validates :user_id     ,presence: true
  validates :customer_id ,presence: true
  validates :movie_id    ,presence: true
  validates :quantity    ,presence: true

  validate :is_available

  belongs_to :customer
  belongs_to :user
  belongs_to :movie
  has_many :return_movies

  private
  def is_available
    movie = Movie.find(self.movie_id)
    total_rented = Transaction.where(movie_id: self.movie_id).sum(:quantity)
    available_copy = movie.total_copy - total_rented
    errors.add(:quantity,"Cannot be provided!") if !self.quantity.nil? && available_copy < self.quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :customers
  has_many :transactions
  has_many :return_movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  helper_method :admin?, :staff?


  def admin?
    current_user.position == "admin"
  end

  def staff?
    current_user.position == "staff"
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:edit,:update,:destroy,:show]

  def index
    @customer = Customer.includes(:transactions).page(params[:page]).per(10)
    @customer = @customer.find(params[:transaction_id]) if params[:transaction_id]
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)
    @customer.user_id = current_user.id
    if @customer.save
      flash[:success] = "Customer successfully added!"
      redirect_to customers_path
    else
      render :new
    end
  end

  def update
    if @customer.update(customer_params)
      flash[:success] = "Customer successfully updated!"
      redirect_to customers_path(page: params[:page])
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:name,:gender,:status,:age,:email,:address)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/rented_movies_controller.rb
class RentedMoviesController < ApplicationController
  def index
    @rented_movies = Movie.includes(:transactions).page(params[:page]).per(10)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:edit,:update]
  include RentedMoviesHelper
  def index
    @transaction = Transaction.includes(:customer,:movie).page(params[:page]).per(10)
    @transaction = @transaction.find(params[:customer_id]).page(params[:id]).per(10) if params[:customer_id]
    @transaction = @transaction.find(params[:rented_movie_id]).page(params[:id]).per(10) if params[:rented_movie_id]
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.create(transaction_params)
    @transaction.user_id = current_user.id
    if @transaction.save
      flash[:success] = "Trasanction done"
      redirect_to transactions_path(page: params[:page])
    else
      render :new
    end
  end

  private
  def transaction_params
    params.require(:transaction).permit(:customer_id,:movie_id,:quantity)
  end

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/rented_movies_helper.rb
module RentedMoviesHelper
  def available_movies(total_copy, rented_movies)
    available_copy = total_copy - rented_movies
  end
end

app/helpers/return_movies_helper.rb
module ReturnMoviesHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "App" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CD-Rental</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <% if admin? %>
            <li><%= link_to "Employees", admin_employees_path %></li>
            <li><%= link_to "Movies", admin_movies_path %></li>
          <% end %>
          <% if staff? %>
            <li><%= link_to "Transaction", transactions_path %></li>
            <li><%= link_to "Return Movies", return_movies_path %></li>
            <li><%= link_to "Customers", customers_path %></li>
            <li><%= link_to "Rented Movies", rented_movies_path %></li>
          <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="navbar-text"><%= current_user.email %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
  <%= bootstrap_flash %>
  <%= yield %>
</div> <!-- /container -->

</body>
</html>

app/views/shared/_messages.html.erb
<% if obj.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h1 class="panel-title">Errors</h1>
    </div>
    <div class="panel-body">
      <ul>
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>